version: '3.1'
services:
    nginx:
        image: nginx
        restart: always
        ports:
            - 8088:80
        volumes:
            - ./nginx/conf.d:/etc/nginx/conf.d
            - ./frontend/dist:/home/hooks
    hook-test:
        container_name: hook-test
        build: ./backend
        ports:
            - 6000:6000