version: "3"
services:
    nginx:
        image: nginx
        restart: always
        ports:
            - 9000:80
        volumes:
            - ./nginx/conf.d:/etc/nginx/conf.d
            - ./frondend/dist:/home/mrHooks
    app-hooks:
        container_name: app-hooks
        build: ./backend
        ports:
            - 3000:3000